services:
  warden:
    image: ghcr.io/johagan94/warden:latest
    container_name: warden
    hostname: warden
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: Australia/Brisbane
      LOG_LEVEL: INFO
      WARDEN_MODE: warden
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    networks:
      - homelab

networks:
  homelab:
    external: true
